Models/Database/Active/Sekolah.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace OrigamiEdu.Models
{
    public class Sekolah{
        public Guid ID { get; set; }

        [Display(Name = "Nama Sekolah")]
        [Required(ErrorMessage="Data tidak boleh kosong!")]
        public string sekolah { get; set; }
        public KabupatenKota fkKabupatenKota { get; set; }
        public KategoriSekolah fkKategoriSekolah { get; set; }
        
        //===========================================================//
        [NotMapped]
        public string mst_primary { get; set; }
        
        [NotMapped]
        public string mst_namaSekolah { get; set; }

        [NotMapped]
        public string mst_KatgName { get; set; }
        
        [NotMapped]
        [Display(Name = "Data Kabupaten")]
        [Required(ErrorMessage="Data tidak boleh kosong!")]
        public string mst_fkKab { get; set; }


        [NotMapped]
        public string mst_loc { get; set; }

        [NotMapped]
        [Display(Name = "Data Kategori Sekolah")]
        [Required(ErrorMessage="Data tidak boleh kosong!")]
        public string mst_primaryKtg { get; set; }
        
        [NotMapped]
        [Display(Name = "Data Provinsi")]
        [Required(ErrorMessage="Data tidak boleh kosong!")]
        public string mst_primaryProvinsi { get; set; }

        [NotMapped]
        public List<Provinsi> listProvinsi { get; set; }

        [NotMapped]
        public List<KabupatenKota> listKabKota { get; set; }
        
        
    }
}

Areas/Administrator/Controllers/SekolahController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using OrigamiEdu.Models;
using OrigamiEdu.Repository;

namespace OrigamiEdu.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    public class SekolahController : Controller
    {
        private readonly Context _context;
        private readonly ILogger<SekolahController> logger;
        private readonly SekolahRepository sekolahRepository;
        private readonly KabupatenKotaRepository kabupatenKotaRepository;
        private readonly ProvinsiRepository provinsiRepository;

        [TempData]
        public string message { get; set; }
        public SekolahController(Context context, ILogger<SekolahController> logger, SekolahRepository sekolahRepository, KabupatenKotaRepository kabupatenKotaRepository, ProvinsiRepository provinsiRepository)
        {
            _context = context;
            this.logger = logger;
            this.sekolahRepository = sekolahRepository;
            this.kabupatenKotaRepository = kabupatenKotaRepository;
            this.provinsiRepository = provinsiRepository;
        }
        
        public async Task<IActionResult> index()
        {
            ViewBag.dataSch = await sekolahRepository.readAll();

            var kat = await sekolahRepository.readKategoriSekolahsAsync();
            ViewBag.dataKtg = kat;

            ViewBag.countAll = await sekolahRepository.countAllSekolah();
            
            return View();
        }
        
        public IActionResult tambah()
        {
            ViewBag.comboProvinsi = _context.Provinsis.Select(p => new SelectListItem{
                Text = p.provinsi,
                Value = p.ID.ToString()
            }).OrderBy(t => t.Text);

            ViewBag.comboKategori = _context.kategoriSekolahs.Select(kt => new SelectListItem{
                Text = kt.namaKategori,
                Value = kt.ID.ToString()
            }).OrderBy(t => t.Text);

            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> tambah(Sekolah sch)
        {
            if(ModelState.IsValid)
            {
                var prv = await provinsiRepository.readOneByID(sch.mst_primaryProvinsi);
                var kbpt = await kabupatenKotaRepository.readSingle(sch.mst_fkKab);
                var kat = await sekolahRepository.readKategoriSekolahByID(sch.mst_primaryKtg);
                kbpt.mst_primaryProvinsi = null;
                if(prv == null || kbpt == null || kat == null)
                {
                    ModelState.AddModelError("mst_primaryProvinsi", "Data tidak valid");
                }
                else{
                    try
                    {
                        if(sch.sekolah.Contains(';'))
                        {
                            string[] split = sch.sekolah.Split(';');
                            var added = "";
                            var state = false;
                            foreach (var item in split)
                            {
                                if(string.IsNullOrEmpty(item) || string.IsNullOrWhiteSpace(item))
                                {
                                    state = true;
                                    continue;
                                }

                                if(!(await sekolahRepository.addSekolah(new Sekolah{
                                    ID = new Guid(),
                                    sekolah = item.Trim(),
                                    fkKabupatenKota = kbpt,
                                    fkKategoriSekolah = kat
                                }))){
                                    state = false;
                                    if(!(string.IsNullOrEmpty(added)))
                                    {
                                        added.Remove(added.Length - 1, 1);
                                    }
                                    break;
                                }else{
                                    state = true;
                                    added += $" {item},";
                                    continue;
                                }
                            }
                            if(!state)
                            {
                                if(string.IsNullOrEmpty(added))
                                {
                                    ModelState.AddModelError("", $"Terjadi kesalahan, pastikan data telah terisi dengan benar!");
                                }else{
                                    ModelState.AddModelError(string.Empty, $"Terjadi kesalahan, pastikan data telah terisi dengan benar!, Sekolah{added} telah berhasil ditambahkan");
                                }
                            }else{
                                message = "Data berhasil ditambahkan!";
                                return RedirectToAction(nameof(index));
                            }
                        }
                        else{
                            if(!(await sekolahRepository.addSekolah(new Sekolah{
                                ID = new Guid(),
                                sekolah = sch.sekolah.Trim(),
                                fkKabupatenKota = kbpt,
                                fkKategoriSekolah = kat
                            })))
                            {
                                ModelState.AddModelError("", $"Terjadi kesalahan, pastikan data telah terisi dengan benar!");
                            }else{
                                message = "Data tersimpan";
                                return RedirectToAction(nameof(index));
                            }
                        }
                    }
                    catch (Exception e)
                    {
                        ModelState.AddModelError("", e.Message);
                    }
                }
            }

            ViewBag.comboProvinsi = _context.Provinsis.Select(p => new SelectListItem{
                Text = p.provinsi,
                Value = p.ID.ToString()
            }).OrderBy(t => t.Text);

            ViewBag.comboKategori = _context.kategoriSekolahs.Select(kt => new SelectListItem{
                Text = kt.namaKategori,
                Value = kt.ID.ToString()
            }).OrderBy(t => t.Text);

            return View(sch);
        }

        public async Task<IActionResult> edit(string ID)
        {
            try
            {
                var result = await sekolahRepository.readOneByID(ID);
                var kategori = await sekolahRepository.readKategoriSekolahsAsync(result.mst_primaryKtg);
                var prov = await provinsiRepository.readAllByID(result.mst_primaryProvinsi);
                var kabupatenKota = await kabupatenKotaRepository.readByProvinsi(result.mst_primaryProvinsi, result.mst_fkKab);

                ViewBag.comboProvinsi = prov.OrderBy(p => p.provinsi).Select(p => new SelectListItem{
                    Text = p.provinsi,
                    Value = p.ID.ToString(),
                    Selected = p.selected
                });

                ViewBag.comboKabupaten = kabupatenKota.OrderBy(k => k.kabupatenKota).Select(k => new SelectListItem{
                    Text = k.kabupatenKota,
                    Value = k.ID.ToString(),
                    Selected = k.selected
                });

                ViewBag.kategori = kategori.OrderBy(kt => kt.namaKategori).Select(kt => new SelectListItem{
                    Text = kt.namaKategori,
                    Value = kt.ID.ToString(),
                    Selected = kt.selected
                });

                return View(result);
            }
            catch (System.Exception e)
            {
                message = e.Message;
                return RedirectToAction(nameof(index));
            }
            
        }
        
        [HttpPost]
        public async Task<IActionResult> edit(Sekolah sch)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    var prv = await provinsiRepository.readOneByID(sch.mst_primaryProvinsi);
                    var kbpt = await kabupatenKotaRepository.readSingle(sch.mst_fkKab);
                    var kat = await sekolahRepository.readKategoriSekolahByID(sch.mst_primaryKtg);
                    kbpt.mst_primaryProvinsi = null;
                    if(sch.sekolah.Contains(';') || prv == null || kbpt == null || kat == null){
                        ModelState.AddModelError("", "Data tidak valid atau terdapat semicolon pada kolom Nama Sekolah!");
                    } 
                    else{
                        if(!(await sekolahRepository.editSekolah(new Sekolah{
                            ID = sch.ID,
                            sekolah = sch.sekolah.Trim(),
                            fkKabupatenKota = kbpt,
                            fkKategoriSekolah = kat
                        })))
                        {
                            ModelState.AddModelError(string.Empty, $"Terjadi kesalahan, pastikan data telah terisi dengan benar!");
                        }else{
                            message = "Data berhasil disimpan!";
                            return RedirectToAction(nameof(index));
                        }
                    }
                }
                catch (Exception e)
                {
                    ModelState.AddModelError(string.Empty, $"{e.Message}");
                }                    
            }

            ViewBag.comboProvinsi = _context.Provinsis.OrderBy(p => p.provinsi).Select(p => new SelectListItem{
                Text = p.provinsi,
                Value = p.ID.ToString(),
                Selected = p.ID.ToString() == sch.mst_primaryProvinsi
            });

Areas/Administrator/Views/Sekolah/dihapus.cshtml
@model IEnumerable<SekolahDump>
@{
    ViewData["Title"] = "Sekolah dihapus";
}

<div class="row">
    <div class="col">
        <h1 class="mt-4">Data Sekolah (dihapus)</h1>
        <hr>
        <div class="float-right">
            <div class="form-inline">
                <div class="form group" style="width: auto;">
                    <input type="text" id="searchQuery" name="query" class="form-control" placeholder="Cari">
                </div>
            </div>
        </div>
        <table class="table table-hover" id="tableSekolah">
            <thead>
                <th class="text-center align-middle">Sekolah</th>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="baris_tabel">
                        <td class="text-center align-middle">@item.sekolah</td>
                        <td class="text-center align-middle">
                            <a style="color: black;" asp-action="pulihkan" asp-controller="Sekolah" asp-area="Administrator" asp-route-ID="@item.ID.ToString()" class="btn btn-outline-primary">Pulihkan</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>
@section Scripts{
    <script>
        if(!("@TempData["message"]" === ""))
        {
            alert("@TempData["message"]");
        }



        $(document).ready(function(){
            var schTable = $("#tableSekolah").DataTable({
                @* "pagingType" : "full_numbers", *@
                "dom":' ltp'
            });
            $('#searchQuery').keyup(function(){
                schTable.search($(this).val()).draw() ;
            });
        })
    </script>
}

Areas/Administrator/Views/Sekolah/edit.cshtml
@{
    ViewData["Title"] = "Admin/Edit Sekolah";
}
@model Sekolah
<h1 class="mt-4">Edit Sekolah</h1>

<form asp-action="edit" method="post">
    <div asp-validation-summary="All"></div>
    <input type="hidden" asp-for="mst_primary">
    <div class="form-group">
        <label class="control-label">Pilih Provinsi</label>
        <select id="comboProvinsi" class="form-control" asp-for="mst_primaryProvinsi" asp-items="@ViewBag.comboProvinsi"> 
            <option value="">Daftar Provinsi</option>
        </select>
        <span asp-validation-for="mst_primaryProvinsi" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="control-label">Pilih Kabupaten/Kota</label>
        <select id="comboKabKota" class="form-control" asp-for="mst_fkKab" asp-items="@ViewBag.comboKabupaten">
            <option value="">Daftar Kabupaten/Kota</option>
        </select>
        <span asp-validation-for="mst_fkKab" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="form-label">Pilih Kategori Sekolah</label>
        <select asp-for="mst_primaryKtg" id="kategoriSekolah" asp-items="@ViewBag.kategori" class="form-control">
            <option value="">Daftar Kategori</option>
        </select>
        <span style="display: block;" asp-validation-for="mst_primaryKtg" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="form-label">Nama Sekolah</label>
        <input type="text" id="school" class="form-control" asp-for="sekolah">
        <span>Contoh: Sekolah A;Sekolah B;Sekolah C</span>
        <span style="display: block;" asp-validation-for="sekolah" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Simpan</button>
        <a href='@Url.Action("index", "Sekolah", new{Area="Administrator"})' class="btn btn-outline-dark">Batal</a>
    </div>
</form>

@section Scripts{
    <script>
        if(!("@TempData["message"]" === ""))
        {
            alert("@TempData["message"]");
        }

        document.getElementById('school').focus();
        
        $(function(){
           $("#comboProvinsi").change(function(){         
              $.post("/Administrator/Sekolah/comboKab", 
                     { ID: $("#comboProvinsi option:selected").val()}, 
                    function(response){
                        if(response == null)
                        {
                            $("#comboKabKota").empty();
                            $("#comboKabKota").append('<option value="">Daftar Kabupaten/Kota</option>');
                        }else{
                            $("#comboKabKota").empty();
                            $("#comboKabKota").append('<option value="">Daftar Kabupaten/Kota</option>');
                            $.each(response, function(index, value){
                                $("#comboKabKota").append('<option value = "'+value.key+'">'+value.kabupatenKota+'</option>');
                            });
                        }
                    }
                ) ;
           });
        });
    </script>
    
}

Areas/Administrator/Views/Sekolah/editKategori.cshtml
@{
    ViewData["Title"] = "Admin/Edit Kategori Sekolah";
}
@model KategoriSekolah
<h1 class="mt-4">Edit Kategori Sekolah</h1>

<form asp-action="editKategori" method="post">
    <span asp-validation-summary="All"></span>
    <input type="hidden" readonly asp-for="mst_primary">
    <div class="form-group">
        <label class="form-label">Nama Kategori Sekolah</label>
        <input id="ctgSchool" class="form-control" asp-for="mst_namaKtg" type="text">
        <span style="display: block;" asp-validation-for="mst_namaKtg" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Simpan</button>
        <a href='@Url.Action("index", "Sekolah", new{Area="Administrator"})' class="btn btn-outline-dark">Batal</a>
    </div>
</form>

@section Scripts{
    <script>
        if(!("@TempData["message"]" === ""))
        {
            alert("@TempData["message"]");
        }

        document.getElementById('ctgSchool').focus();
    </script>
    
}

Areas/Administrator/Views/Sekolah/index.cshtml
@{
    ViewData["Title"] = "Data Sekolah";
}
<div class="row">
    <div class="col">
        <h1 class="mt-4">Data Kategori Sekolah</h1>
        <hr>
        <div class="float-right">
            <div class="form-inline">
                <div class="form group" style="width: auto;">
                    <input type="text" id="searchQueryKtg" name="query" class="form-control" placeholder="Cari">
                </div>
            </div>
        </div>
        <a style="margin-bottom: 10pt;" href='@Url.Action("tambahKategori", "Sekolah", new{Area = "Administrator"})' class="btn btn-outline-primary">
                <img width="20px" src="/svgs/regular/plus-square.svg" alt="Tambah">
                Tambah Kategori Sekolah
        </a>
        <table class="table table-hover" id="tableKtgSekolah">
            <thead>
                <th class="text-center align-middle">Kategori</th>
                <th class="text-center align-middle">Aksi</th>
            </thead>
            <tbody>
                @foreach (var item in @ViewBag.dataKtg)
                {
                    <tr class="baris_tabel">
                        <td class="text-center align-middle">@item.namaKategori</td>
                        <td class="text-center align-middle">
                            <a style="color: black;" href='@Url.Action("editKategori", "Sekolah", new{Area = "Administrator", ID = @item.ID.ToString()})' class="btn btn-outline-warning"><img style="border-right: 10px;" width="20px" src="/svgs/regular/edit.svg" alt="Edit">Edit</a>
                            <a style="color: black;" onclick="hapusKategori('@item.ID.ToString()')" class="btn btn-outline-warning"><img style="border-right: 10px;" width="20px" src="/svgs/regular/trash-alt.svg" alt="Hapus">Hapus</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col">
        <h1 class="mt-4">Data Sekolah</h1>
        <hr>
        <div class="float-right">
            <div class="form-inline">
                <div class="form group" style="width: auto;">
                    <input type="text" id="searchQuery" name="query" class="form-control" placeholder="Cari">
                </div>
            </div>
        </div>
        <a style="margin-bottom: 10pt;" href='@Url.Action("tambah", "Sekolah", new{Area = "Administrator"})' class="btn btn-outline-primary">
                <img width="20px" src="/svgs/regular/plus-square.svg" alt="Tambah">
                Tambah Sekolah
        </a>
        <a style="margin-bottom: 10pt; width: auto;" asp-action="dihapus" asp-controller="Sekolah" asp-area="Administrator" class="btn btn-outline-primary">
                Data Sekolah dihapus
        </a>
        <h5 class="mt-2 text-info">Saat ini terdapat @ViewBag.countAll sekolah terdaftar</h5>
        <table class="table table-hover" id="tableSekolah">
            <thead>
                <th class="text-center align-middle">Sekolah</th>
                <th class="text-center align-middle">Lokasi</th>
                <th class="text-center align-middle">Kategori Sekolah</th>
                <th class="text-center align-middle">Aksi</th>
            </thead>
            <tbody>
                @foreach (var item in @ViewBag.datasch)
                {
                    <tr class="baris_tabel">
                        <td class="text-center align-middle">@item.sekolah</td>
                        <td class="text-center align-middle">@item.mst_loc</td>
                        <td class="text-center align-middle">@item.mst_KatgName</td>
                        <td class="text-center align-middle">
                            <a style="color: black;" href='@Url.Action("edit", "Sekolah", new{Area = "Administrator", ID = @item.ID})' class="btn btn-outline-warning"><img style="border-right: 10px;" width="20px" src="/svgs/regular/edit.svg" alt="Edit">Edit</a>
                            <a style="color: black;" onclick="hapus('@item.ID')" class="btn btn-outline-warning"><img style="border-right: 10px;" width="20px" src="/svgs/regular/trash-alt.svg" alt="Hapus">Hapus</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>


@section Scripts{
    <script>
        if(!("@TempData["message"]" === ""))
        {
            alert("@TempData["message"]");
        }



        $(document).ready(function(){
            var schTable = $("#tableSekolah").DataTable({
                @* "pagingType" : "full_numbers", *@
                "dom":' ltp'
            });
            $('#searchQuery').keyup(function(){
                schTable.search($(this).val()).draw() ;
            });
            var ktgTable = $("#tableKtgSekolah").DataTable({
                @* "pagingType" : "full_numbers", *@
                "dom":' ltp'
            });
            $('#searchQueryKtg').keyup(function(){
                ktgTable.search($(this).val()).draw() ;
            });
        })


        let hapus = function(param)
        {
            if(window.confirm("Yakin ingin menghapus data ini?"))
            {
                window.location.href = 'Sekolah/hapusSekolah/' + param;
            }
        }

        let hapusKategori = function()
        {
            if(window.confirm("Yakin ingin menghapus data ini?"))
            {
                window.location.href = 'Sekolah/hapusKategori/' + param;
            }
        }

        
    </script>
}

Areas/Administrator/Views/Sekolah/tambah.cshtml
@{
    ViewData["Title"] = "Admin/Tambah Sekolah";
}
@model Sekolah
<h1 class="mt-4">Tambah Sekolah</h1>

<form asp-action="tambah" method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label class="control-label">Pilih Provinsi</label>
        <select id="comboProvinsi" class="form-control" asp-for="mst_primaryProvinsi" asp-items="@ViewBag.comboProvinsi"> 
            <option value="">Daftar Provinsi</option>
        </select>
        <span asp-validation-for="mst_primaryProvinsi" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="control-label">Pilih Kabupaten/Kota</label>
        <select id="comboKabKota" class="form-control" asp-for="mst_fkKab" asp-items="@ViewBag.comboKabupaten">
            <option value="">Daftar Kabupaten/Kota</option>
        </select>
        <span asp-validation-for="mst_fkKab" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="form-label">Pilih Kategori Sekolah</label>
        <select asp-for="mst_primaryKtg" id="kategoriSekolah" asp-items="@ViewBag.comboKategori" class="form-control">
            <option value="">Daftar Kategori</option>
        </select>
        <span style="display: block;" asp-validation-for="mst_primaryKtg" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="form-label">Nama Sekolah</label>
        <textarea id="school" class="form-control" asp-for="sekolah"></textarea>
        <span style="display: block;">Untuk input lebih dari satu, pisahkan tiap-tiap <i>item</i> dengan <strong>semicolon (;)</strong></span>
        <span>Contoh: Sekolah A;Sekolah B;Sekolah C</span>
        <span style="display: block;" asp-validation-for="sekolah" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Simpan</button>
        <a href='@Url.Action("index", "Sekolah", new{Area="Administrator"})' class="btn btn-outline-dark">Batal</a>
    </div>
</form>

@section Scripts{
    <script>
        if(!("@TempData["message"]" === ""))
        {
            alert("@TempData["message"]");
        }

        document.getElementById('school').focus();
        
        $(function(){
           $("#comboProvinsi").change(function(){         
              $.post("/Administrator/Sekolah/comboKab", 
                     { ID: $("#comboProvinsi option:selected").val()}, 
                    function(response){
                        if(response == null)
                        {
                            $("#comboKabKota").empty();
                            $("#comboKabKota").append('<option value="">Daftar Kabupaten/Kota</option>');
                        }else{
                            $("#comboKabKota").empty();
                            $("#comboKabKota").append('<option value="">Daftar Kabupaten/Kota</option>');
                            $.each(response, function(index, value){
                                $("#comboKabKota").append('<option value = "'+value.key+'">'+value.kabupatenKota+'</option>');
                            });
                        }
                    }
                ) ;
           });
        });
    </script>
    
}

Areas/Administrator/Views/Sekolah/tambahKategori.cshtml
@{
    ViewData["Title"] = "Admin/Tambah Kategori Sekolah";
}
@model KategoriSekolah
<h1 class="mt-4">Tambah Kategori Sekolah</h1>

<form asp-action="tambahKategori" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label class="form-label">Nama Kategori Sekolah</label>
        <textarea id="ctgSchool" class="form-control" asp-for="namaKategori"></textarea>
        <span style="display: block;">Untuk input lebih dari satu, pisahkan tiap-tiap <i>item</i> dengan <strong>semicolon (;)</strong></span>
        <span>Contoh: Kategori Sekolah A;Kategori Sekolah B</span>
        <span style="display: block;" asp-validation-for="namaKategori" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Simpan</button>
        <a href='@Url.Action("index", "Sekolah", new{Area="Administrator"})' class="btn btn-outline-dark">Batal</a>
    </div>
</form>

@section Scripts{
    <script>
        if(!("@TempData["message"]" === ""))
        {
            alert("@TempData["message"]");
        }

        document.getElementById('ctgSchool').focus();
    </script>
    
}