Models/Database/Active/universitas.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OrigamiEdu.Models
{
    public class Universitas 
    {
        public Guid ID { get; set; }

        [Display(Name = "Nama Universitas")]
        [Required(ErrorMessage="Data tidak boleh kosong!")]
        public string universitas { get; set; }
        public Provinsi fkProvinsi { get; set; }
        public KategoriUniversitas fkKategoriUniversitas { get; set; }

        // ====================================================================================== //

        [NotMapped]
        public string mst_primary { get; set; }
        
        [NotMapped]
        
        public string mst_namaUniv { get; set; }
        
        [NotMapped]
        [Display(Name = "Data Provinsi")]
        [Required(ErrorMessage="Data tidak boleh kosong!")]
        public string mst_fkProvinsi { get; set; }

        [NotMapped]
        [Display(Name = "Data Kategori Universitas")]
        [Required(ErrorMessage="Data tidak boleh kosong!")]
        public string mst_fkKatUniv { get; set; }
    }
}

Areas/Administrator/Controllers/UniversitasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using OrigamiEdu.Models;
using OrigamiEdu.Repository;

namespace OrigamiEdu.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    public class UniversitasController : Controller
    {
        private readonly Context context;
        private readonly ILogger<UniversitasController> logger;
        private readonly UniversitasRepository universitasRepository;
        private readonly ProvinsiRepository provinsiRepository;

        [TempData]
        public string message { get; set; }

        public UniversitasController(Context context, ILogger<UniversitasController> logger, UniversitasRepository universitasRepository, ProvinsiRepository provinsiRepository)
        {
            this.context = context;
            this.logger = logger;
            this.universitasRepository = universitasRepository;
            this.provinsiRepository = provinsiRepository;
        }
// ============================================================================================================== //
        public async Task<IActionResult> index()
        {
            ViewBag.Universitas = await universitasRepository.readUniversitasAsync();

            ViewBag.kategoriUniversitas = await universitasRepository.readKategoriUniversitas();

            ViewBag.countAll = await universitasRepository.countUniversitasAsync();
            return View();
        }

        public IActionResult tambahUniversitas()
        {
            ViewBag.comboKategori = context.kategoriUniversitas.OrderBy(kU => kU.katgUniv).Select(kU => new SelectListItem{
                Value = kU.ID.ToString(),
                Text = kU.katgUniv
            });

            ViewBag.comboProvinsi = context.Provinsis.OrderBy(p => p.provinsi).Select(p => new SelectListItem{
                Text = p.provinsi,
                Value = p.ID.ToString()
            });

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> tambahUniversitas(Universitas _universitas)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    var ktg = await universitasRepository.readSingleKategoriUniversitas(_universitas.mst_fkKatUniv);
                    var prv = await provinsiRepository.readOneByID(_universitas.mst_fkProvinsi);
                    if(ktg == null || prv == null)
                    {
                        ModelState.AddModelError("", "Terjadi kesalahan, data tidak valid!");
                    }
                    else{
                        if(_universitas.universitas.Contains(';'))
                        {
                            string[] splitUniv = _universitas.universitas.Split(';');
                            var added = "";
                            var state = false;
                            foreach (var item in splitUniv)
                            {
                                if(string.IsNullOrEmpty(item) || string.IsNullOrWhiteSpace(item))
                                {
                                    state = true;
                                    continue;
                                }

                                if(!(await universitasRepository.addUniversitas(new Universitas{
                                    ID = new Guid(),
                                    universitas = item.Trim(),
                                    fkKategoriUniversitas = ktg,
                                    fkProvinsi = prv
                                })))
                                {
                                    state = false;
                                    if(!(string.IsNullOrEmpty(added))){added.Remove(added.Length-1, 1);}
                                    ModelState.AddModelError("", "Terjadi kesalahan, data tidak valid!");
                                    break;
                                }else{
                                    added += $" {item.Trim()},";
                                    state = true;
                                }
                            }
                            if(!state)
                            {
                                if(!(string.IsNullOrEmpty(added))){ModelState.AddModelError("", "Terjadi kesalahan, data tidak valid!");}
                                else{ModelState.AddModelError("", $"Terjadi kesalahan, data tidak valid!. Universitas{added} telah berhasil ditambahkan");}
                            }
                            else{message = "Data berhasil disimpan!"; return RedirectToAction(nameof(index));}
                        }
                        else{
                            if(!(await universitasRepository.addUniversitas(new Universitas{
                                ID = new Guid(),
                                universitas = _universitas.mst_namaUniv.Trim(),
                                fkKategoriUniversitas = ktg,
                                fkProvinsi = prv
                            }))){
                                ModelState.AddModelError("", "Terjadi kesalahan, data tidak valid!");
                            }else{
                                message = "Data berhasil disimpan";
                                return RedirectToAction(nameof(index));
                            }
                        }
                    }
                    
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }

            ViewBag.comboKategori = context.kategoriUniversitas.OrderBy(kU => kU.katgUniv).Select(kU => new SelectListItem{
                Value = kU.ID.ToString(),
                Text = kU.katgUniv,
                Selected = kU.ID.ToString() == _universitas.mst_fkKatUniv ? true : false
            });
            ViewBag.comboProvinsi = context.Provinsis.OrderBy(p => p.provinsi).Select(p => new SelectListItem{
                Text = p.provinsi,
                Value = p.ID.ToString(),
                Selected = p.ID.ToString() == _universitas.mst_fkProvinsi ? true : false
            });

            return View(_universitas);
        }

        public async Task<IActionResult> editUniversitas(string ID)
        {
            try
            {
                var data = await universitasRepository.readSingleUniversitasAsync(ID);

                ViewBag.comboKategori = context.kategoriUniversitas.OrderBy(kU => kU.katgUniv).Select(kU => new SelectListItem{
                    Value = kU.ID.ToString(),
                    Text = kU.katgUniv,
                    Selected = kU.ID.ToString() == data.mst_fkKatUniv
                });
                ViewBag.comboProvinsi = context.Provinsis.OrderBy(p => p.provinsi).Select(p => new SelectListItem{
                    Text = p.provinsi,
                    Value = p.ID.ToString(),
                    Selected = p.ID.ToString() == data.mst_fkProvinsi
                });

                return View(data);
            }
            catch (Exception e)
            {
                message = e.Message;
                return RedirectToAction(nameof(index));
            }
        }

        [HttpPost]
        public async Task<IActionResult> editUniversitas(Universitas _universitas)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    var ktg = await universitasRepository.readSingleKategoriUniversitas(_universitas.mst_fkKatUniv);
                    var prv = await provinsiRepository.readOneByID(_universitas.mst_fkProvinsi);
                    if(ktg == null || prv == null)
                    {
                        ModelState.AddModelError("", "Terjadi kesalahan, data tidak valid!");
                    }
                    else{

                        if(_universitas.universitas.Contains(';'))
                        {
                            ModelState.AddModelError("universitas", "Penggunaan semicolon tidak dibolehkan!");
                        }else{
                            if(!(await universitasRepository.editUniversitas(new Universitas{
                                ID = _universitas.ID,
                                universitas = _universitas.universitas,
                                fkKategoriUniversitas = ktg,
                                fkProvinsi = prv
                            }))){
                                ModelState.AddModelError("", "Terjadi kesalahan, data tidak valid!");
                            }else{
                                message = "Data berhasil disimpan";
                                return RedirectToAction(nameof(index));
                            }
                        }
                    }
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }
            ViewBag.comboKategori = context.kategoriUniversitas.OrderBy(kU => kU.katgUniv).Select(kU => new SelectListItem{
                Value = kU.ID.ToString(),
                Text = kU.katgUniv,
                Selected = kU.ID.ToString() == _universitas.mst_fkKatUniv ? true : false
            });
            ViewBag.comboProvinsi = context.Provinsis.OrderBy(p => p.provinsi).Select(p => new SelectListItem{
                Text = p.provinsi,
                Value = p.ID.ToString(),
                Selected = p.ID.ToString() == _universitas.mst_fkProvinsi ? true : false
            });
            return View(_universitas);
        }

        public async Task<IActionResult> hapusUniversitas(string ID)
        {
            try
            {

Areas/Administrator/Views/Universitas/editKategoriUniversitas.cshtml
@{
    ViewData["Title"] = "Admin/Edit Kategori Universitas";
}
@model KategoriUniversitas
<div class="text-center">
    <h4>Edit Data Kategori Universitas</h4>
</div>

<form asp-action="editKategoriUniversitas" method="post">
    <div asp-validation-summary="All"></div>
    <input type="hidden" readonly asp-for="ID">
    <div class="form-group">
        <label class="form-label">Nama Kategori Universitas</label>
        <input id="katUniv" class="form-control" asp-for="katgUniv">
        <span style="display: block;" asp-validation-for="katgUniv" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Simpan</button>
        <a href='@Url.Action("index", "Universitas", new{Area="Administrator"})' class="btn btn-outline-dark">Batal</a>
    </div>
</form>

@section Scripts{
    <script>
        if(!("@TempData["message"]" === ""))
        {
            alert("@TempData["message"]");
        }

        document.getElementById('katUniv').focus();
    </script>
    
}

Areas/Administrator/Views/Universitas/editUniversitas.cshtml
@{
    ViewData["Title"] = "Admin/Edit Universitas";
}
@model Universitas
<div class="text-center">
    <h4>Edit Data Universitas</h4>
</div>

<form asp-action="editUniversitas" method="post">
    <div asp-validation-summary="All"></div>
    <input type="hidden" readonly asp-for="ID">
    <div class="form-group">
        <label class="control-label">Provinsi</label>
        <select class="form-control" asp-for="mst_fkProvinsi" asp-items="@ViewBag.comboProvinsi">
            <option value="">Daftar Provinsi</option>
        </select>
        <span style="display: block;" asp-validation-for="mst_fkProvinsi" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="control-label">Kategori Universitas</label>
        <select class="form-control" asp-for="mst_fkKatUniv" asp-items="@ViewBag.comboKategori">
            <option value="">Daftar Kategori Universitas</option>
        </select>
        <span style="display: block;" asp-validation-for="mst_fkKatUniv" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="form-label">Nama Universitas</label>
        <input id="namaUniv" class="form-control" asp-for="universitas" type="text">
        <span style="display: block;" asp-validation-for="universitas" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Simpan</button>
        <a href='@Url.Action("index", "Universitas", new{Area="Administrator"})' class="btn btn-outline-dark">Batal</a>
    </div>
</form>

@section Scripts{
    <script>
        if(!("@TempData["message"]" === ""))
        {
            alert("@TempData["message"]");
        }

        document.getElementById('namaUniv').focus();
    </script>
    
}

Areas/Administrator/Views/Universitas/index.cshtml
@{
    ViewData["Title"] = "Data Universitas";
}
<div class="row">
    <div class="col">
        <h1 class="mt-4">Data Kategori Universitas</h1>
        <hr>
        <div class="float-right">
            <div class="form-inline">
                <div class="form group" style="width: auto;">
                    <input type="text" id="searchQueryKtg" name="query" class="form-control" placeholder="Cari">
                </div>
            </div>
        </div>
        <a style="margin-bottom: 10pt;" href='@Url.Action("tambahKategoriUniversitas", "Universitas", new{Area = "Administrator"})' class="btn btn-outline-primary">
                <img width="20px" src="/svgs/regular/plus-square.svg" alt="Tambah">
                Tambah Kategori Universitas
        </a>
        <table class="table table-hover" id="tableKtgUniversitas">
            <thead>
                <th class="text-center align-middle">Kategori</th>
                <th class="text-center align-middle">Aksi</th>
            </thead>
            <tbody>
                @foreach (var item in @ViewBag.kategoriUniversitas)
                {
                    <tr class="baris_tabel">
                        <td class="text-center align-middle">@item.katgUniv</td>
                        <td class="text-center align-middle">
                            <a style="color: black;" href='@Url.Action("editKategoriUniversitas", "Universitas", new{Area = "Administrator", ID = @item.ID.ToString()})' class="btn btn-outline-warning"><img style="border-right: 10px;" width="20px" src="/svgs/regular/edit.svg" alt="Edit">Edit</a>
                            <a style="color: black;" onclick="hapusKategori('@item.ID.ToString()')" class="btn btn-outline-warning"><img style="border-right: 10px;" width="20px" src="/svgs/regular/trash-alt.svg" alt="Hapus">Hapus</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col">
        <h1 class="mt-4">Data Universitas</h1>
        <hr>
        <div class="float-right">
            <div class="form-inline">
                <div class="form group" style="width: auto;">
                    <input type="text" id="searchQuery" name="query" class="form-control" placeholder="Cari">
                </div>
            </div>
        </div>
        <a style="margin-bottom: 10pt;" href='@Url.Action("tambahUniversitas", "Universitas", new{Area = "Administrator"})' class="btn btn-outline-primary">
                <img width="20px" src="/svgs/regular/plus-square.svg" alt="Tambah">
                Tambah Universitas
        </a>
        <h5 class="mt-2 text-info">Saat ini terdapat @ViewBag.countAll sekolah terdaftar</h5>
        <table class="table table-hover" id="tableUniversitas">
            <thead>
                <th class="text-center align-middle">Universitas</th>
                <th class="text-center align-middle">Provinsi</th>
                <th class="text-center align-middle">Kategori Universitas</th>
                <th class="text-center align-middle">Aksi</th>
            </thead>
            <tbody>
                @foreach (var item in @ViewBag.Universitas)
                {
                    <tr class="baris_tabel">
                        <td class="text-center align-middle">@item.universitas</td>
                        <td class="text-center align-middle">@item.mst_fkProvinsi</td>
                        <td class="text-center align-middle">@item.mst_fkKatUniv</td>
                        <td class="text-center align-middle">
                            <a style="color: black;" href='@Url.Action("updateStatistik", "Universitas", new{Area = "Administrator", ID = @item.ID.ToString()})' class="btn btn-outline-info"><img style="border-right: 10px;" width="20px" src="/svgs/regular/edit.svg" alt="Edit">Statistik</a>
                            <a style="color: black;" href='@Url.Action("editUniversitas", "Universitas", new{Area = "Administrator", ID = @item.ID.ToString()})' class="btn btn-outline-warning"><img style="border-right: 10px;" width="20px" src="/svgs/regular/edit.svg" alt="Edit">Edit</a>
                            <a style="color: black;" onclick="hapus('@item.ID.ToString()')" class="btn btn-outline-warning"><img style="border-right: 10px;" width="20px" src="/svgs/regular/trash-alt.svg" alt="Hapus">Hapus</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>


@section Scripts{
    <script>
        if(!("@TempData["message"]" === ""))
        {
            alert("@TempData["message"]");
        }



        $(document).ready(function(){
            var schTable = $("#tableUniversitas").DataTable({
                @* "pagingType" : "full_numbers", *@
                "dom":' ltp'
            });
            $('#searchQuery').keyup(function(){
                schTable.search($(this).val()).draw() ;
            });
            var ktgTable = $("#tableKtgUniversitas").DataTable({
                @* "pagingType" : "full_numbers", *@
                "dom":' ltp'
            });
            $('#searchQueryKtg').keyup(function(){
                ktgTable.search($(this).val()).draw() ;
            });
        })


        let hapus = function(param)
        {
            if(window.confirm("Yakin ingin menghapus data ini?"))
            {
                window.location.href = 'Universitas/hapusUniversitas/' + param;
            }
        }

        let hapusKategori = function()
        {
            if(window.confirm("Yakin ingin menghapus data ini?"))
            {
                window.location.href = 'Universitas/hapusKategoriUniversitas/' + param;
            }
        }

        
    </script>
}

Areas/Administrator/Views/Universitas/tambahKategoriUniversitas.cshtml
@{
    ViewData["Title"] = "Admin/Tambah Kategori Universitas";
}
@model KategoriUniversitas
<div class="text-center">
    <h4>Tambah Data Kategori Universitas</h4>
</div>

<form asp-action="tambahKategoriUniversitas" method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label class="control-label">Nama Kategori Universitas</label>
        <textarea id="katUniv" class="form-control" asp-for="katgUniv"></textarea>
        <span style="display: block;">Untuk input lebih dari satu, pisahkan tiap-tiap <i>item</i> dengan <strong>semicolon (;)</strong></span>
        <span>Contoh: Kategori Universitas A;Kategori Universitas B;Kategori Universitas C</span>
        <span style="display: block;" asp-validation-for="katgUniv" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Simpan</button>
        <a href='@Url.Action("index", "Universitas", new{Area="Administrator"})' class="btn btn-outline-dark">Batal</a>
    </div>
</form>

@section Scripts{
    <script>
        if(!("@TempData["message"]" === ""))
        {
            alert("@TempData["message"]");
        }

        document.getElementById('katUniv').focus();
    </script>
    
}

Areas/Administrator/Views/Universitas/tambahUniversitas.cshtml
@{
    ViewData["Title"] = "Admin/Tambah Universitas";
}
@model Universitas
<div class="text-center">
    <h4>Tambah Data Universitas</h4>
</div>

<form asp-action="tambahUniversitas" method="post">
    <div asp-validation-summary="All"></div>
    @* <input type="hidden" readonly asp-for="mst_primary"> *@
    <div class="form-group">
        <label class="control-label">Provinsi</label>
        <select class="form-control" asp-for="mst_fkProvinsi" asp-items="@ViewBag.comboProvinsi">
            <option value="">Daftar Provinsi</option>
        </select>
        <span style="display: block;" asp-validation-for="mst_fkProvinsi" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="control-label">Kategori Universitas</label>
        <select class="form-control" asp-for="mst_fkKatUniv" asp-items="@ViewBag.comboKategori">
            <option value="">Daftar Kategori Universitas</option>
        </select>
        <span style="display: block;" asp-validation-for="mst_fkKatUniv" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="form-label">Nama Universitas</label>
        <textarea class="form-control" id="namaUniv" class="form-control" asp-for="universitas"></textarea>
        <span style="display: block;">Untuk input lebih dari satu, pisahkan tiap-tiap <i>item</i> dengan <strong>semicolon (;)</strong></span>
        <span>Contoh: Universitas A;Universitas B;Universitas C</span>
        <span style="display: block;" asp-validation-for="universitas" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Simpan</button>
        <a href='@Url.Action("index", "Universitas", new{Area="Administrator"})' class="btn btn-outline-dark">Batal</a>
    </div>
</form>

@section Scripts{
    <script>
        if(!("@TempData["message"]" === ""))
        {
            alert("@TempData["message"]");
        }

        document.getElementById('namaUniv').focus();
    </script>
    
}

Areas/Administrator/Views/Universitas/updateStatistik.cshtml
@model updateStatsView
@{
    ViewData["Title"] = $"Statistik {Model.namaUniv}";
}
<div class="row">
    <div class="col">
        <div class="text-center">
            <h1>Data Statistik @Model.namaUniv</h1>
            
        </div>
        <hr>
        
        <form asp-action="updateStatistik" id="form">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="row" id="FormROW">
                <input type="hidden" readonly asp-for="@Model.idUniv">
                @* <input type="hidden" readonly asp-for="objUniversitas.universitas" value="@Model.namaUniv"> *@
                @for (int i = 0; i < Model.lists.Count; i++)
                {
                    <div class="col-md-4 form-statistik border border-dark rounded" style="padding: 0.25rem; margin-bottom: 0.25rem; mr-2">
                        <input type="hidden" asp-for="@Model.lists[i].ID" readonly>
                        <div class="form-group">
                            <label class="control-label">Tahun</label>
                            <input type="number" asp-for="@Model.lists[i].year" class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="control-label">Kuota</label>
                            <input type="number" asp-for="@Model.lists[i].kuota" class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="control-label">Peminat</label>
                            <input type="number" asp-for="@Model.lists[i].peminat" class="form-control">
                        </div>
                        <div class="float-right">
                            <button class="btn btn-outline-danger" onclick="deleteStats('@Model.lists[i].ID', '@Model.lists[i].year')">Hapus Statistik</button>
                        </div>
                    </div>
                }
            </div>
            <div class="col-sm-12 border border-info rounded" id="form-btns" style="padding: 0.75rem;">
                <a class="btn btn-outline-info" onclick="addField()">
                    <img style="border-right: 10px;" width="20px" src="/svgs/regular/plus-square.svg" alt="Edit">
                    Tambah Kolom Statistik
                </a>
                <button class="btn btn-outline-primary" type="submit">Simpan Perubahan</button>
                <a class="btn btn-outline-danger" onclick="quit()">Batal</a>
            </div>
        </form>

    </div>
</div>

@section Scripts
{
    <script>
        if(!("@TempData["message"]" === ""))
        {
            alert("@TempData["message"]");
        }

        let deleteStats = function(paramID, paramYr, index)
        {
            if(window.confirm("Hapus statistik tahun " + paramYr + " ?")){
                window.location.href = "/Administrator/Universitas/hapusStatistik/" + paramID;
            }
        }

        let generateView = function(param, index)
        {
            let form_control = document.createElement("div");
            form_control.className = "form-group";

            let label = document.createElement("label");
            label.className = "control-label";
            let text = document.createTextNode(param);
            label.appendChild(text);
            let input = document.createElement("input");
            input.type = "number";
            input.className = "form-control";
            if(param === "Tahun")
            {
                input.setAttribute("name", "lists[" + index + "].year");
                input.setAttribute("id", "lists_" + index + "__year");
            }else if(param == "Kuota")
            {
                input.setAttribute("name", "lists[" + index + "].kuota");
                input.setAttribute("id", "lists_" + index + "__kuota");
            }else if(param === "Peminat")
            {
                input.setAttribute("name", "lists[" + index + "].peminat");
                input.setAttribute("id", "lists_" + index + "__peminat");
            }
            form_control.appendChild(label);
            form_control.appendChild(input);

            return(form_control);
        }

        let addField = function()
        {
            let idx = document.getElementsByClassName("form-statistik").length;



            if((idx!=0))
            {
                let nameYr = "lists_" + (idx-1).toString() + "__year";
                let nameQt = "lists_" + (idx-1).toString() + "__kuota";
                let namePm = "lists_" + (idx-1).toString() + "__peminat";

                if(document.getElementById(nameYr).value === "" || document.getElementById(nameQt).value === "" || document.getElementById(namePm).value === "")
                {
                    alert("Pastikan data telah terisi dengan benar sebelum menambah form");
                    return;
                }
            } 

            


            let container = document.createElement("div");
            container.className = "col-md-4 form-statistik border border-dark rounded";
            container.style.marginBottom = "0.25rem";
            container.style.padding = "0.25rem";
            

            let createInput = document.createElement("input");
            createInput.type = "hidden";
            createInput.name = "lists[" + idx + "].ID";
            createInput.id = "lists_" + idx + "__ID";
            createInput.value = "@Guid.Empty"
            createInput.setAttribute("readonly", "");

            container.appendChild(createInput);

            let tahun = generateView("Tahun", idx);
            let kuota = generateView("Kuota", idx);
            let peminat = generateView("Peminat", idx);

            container.appendChild(tahun);
            container.appendChild(kuota);
            container.appendChild(peminat);

            document.getElementById("FormROW").appendChild(container);
        }

        let quit = function()
        {
            if(window.confirm("Anda akan keluar dari menu edit statistik dan membatalkan semua perubahan yang anda lakukan. Lanjutkan?"))
            {
                window.location.href = "/Administrator/Universitas/";
            }
        }


        @* ================================== UNUSED ================================== *@
        @* ============================================================================ *@

        @* $(function(){
           $("#saveForm").click(function(){
               var registered = $("input[name=keyID]").length;
               for(var i = 0; i < registered; i++)
               {
                   for(var j = i + 1; j < registered; j++)
                   {
                       if((document.getElementsByName('year')[i].value == document.getElementsByName('year')[j]).value || (document.getElementsByName('year')[i].value === document.getElementsByName('year')[j].value))
                       {
                           alert("Pastikan data telah terisi dengan benar, dan tidak terdapat tahun ganda");
                           return false;
                       }
                   }
               }

               var error = 0;

               for(var i = 0; i < registered; i++)
               {
                   $.post("/Administrator/Universitas/updateStatistik", 
                   { idStats : $("input[name=keyID]:eq("+i+")").val()
                    , idUniversitas : $("#primaryUniversitas").val()
                    , yr : $("input[name=year]:eq("+i+")").val()
                    , kuota : $("input[name=kuota]:eq("+i+")").val()
                    , peminat : $("input[name=peminat]:eq("+i+")").val()},
                    function(response){
                        if(response === "OK")
                        {
                            error += 0;
                        }else{
                            error += 1;
                        }
                    }
                    ) ;
               }

               if(!(error == 0))
               {
                   alert("Beberapa data tidak dapat disimpan!");
               }
               else{
                   alert("Data berhasil disimpan");
                   window.location.href = "/Administrator/Universitas/";
                   return;
               }

           });
        }); *@

        @* ============================================================================ *@
        @* ============================================================================ *@


    </script>
}