Models/Database/Active/Provinsi.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OrigamiEdu.Models
{
    public class Provinsi
    {
        public Guid ID { get; set; }

        [Display(Name = "Nama Provinsi")]
        [Column(TypeName = "varchar(25)")]
        [Required]
        public string provinsi { get; set; }
        
        [NotMapped]
        public string mst_primary { get; set; }
        
        [NotMapped]
        public string mst_namaProvinsi { get; set; }
        
        [NotMapped]
        public bool selected { get; set; }
        
    }
}

Areas/Administrator/Controllers/ProvinsiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OrigamiEdu.Helper;
using OrigamiEdu.Models;
using OrigamiEdu.Repository;

namespace OrigamiEdu.Areas.Administrator.Controllers
{
    [Authorize(Roles = "Administrator")]
    [Area("Administrator")]
    public class ProvinsiController : Controller
    {
        private readonly Context _context;
        private readonly ProvinsiRepository provinsiRepository;

        [TempData]
        public string message { get; set; }

        public ProvinsiController(Context context, ProvinsiRepository provinsiRepository)
        {
            _context = context;
            this.provinsiRepository = provinsiRepository;
        }
        
        public async Task<IActionResult> index()
        {
            /* var data = (from p in _context.Provinsis select new Provinsi{
                mst_primary = p.ID.ToString(),
                mst_namaProvinsi = p.provinsi
            }).OrderBy(p => p.mst_namaProvinsi).ToList(); */
            var data = await provinsiRepository.readAll();
            return View(data.OrderBy(i => i.provinsi));
        }

        [HttpGet]
        public async Task<IActionResult> addOrEdit(string ID = "")
        {
            if(string.IsNullOrEmpty(ID))
            {
                return View(new Provinsi{ID = Guid.Empty});
            }
            else
            {
                var data = await provinsiRepository.readOneByID(ID);

                if(data == null)
                {
                    message = "Terjadi kesalahan, provinsi tidak tersedia";
                    return RedirectToAction(nameof(index));
                }
                return View(data);
            }
        }

        /* [HttpPost]
        public async Task<IActionResult> addOrEdit([Bind("ID", "nama")] Provinsi modProvinsi)
        {
            if(modProvinsi.ID == Guid.Empty)
            {
                if(modProvinsi.provinsi.Contains(';'))
                {
                    string[] splitted = modProvinsi.provinsi.Split(';');
                    string added = "";
                    var state = false;
                    foreach (var str in splitted)
                    {
                        if(string.IsNullOrEmpty(str) || string.IsNullOrWhiteSpace(str))
                        {
                            state = true;
                            continue;
                        }

                        if(!(await provinsiRepository.add(new Provinsi{ID = new Guid(),provinsi = str.Trim()})))
                        {
                            if(!(string.IsNullOrEmpty(added)))
                            {
                                added.Remove(added.Length - 1, 1);
                            }
                            state = false;
                            break;
                        }
                        else{
                            added += $" {str},";
                            state = true;
                            continue;
                        }
                    }
                    if(!state)
                    {
                        if(!(string.IsNullOrEmpty(added)))
                        {
                            ModelState.AddModelError(string.Empty, $"Terjadi kesalahan, pastikan data telah terisi dengan benar!, Provinsi{added} telah berhasil ditambahkan");
                        }else{
                            ModelState.AddModelError(string.Empty, $"Terjadi kesalahan, pastikan data telah terisi dengan benar!");
                        }
                    }else{
                        message = "Data Berhasil Disimpan";
                        // return RedirectToAction(nameof(index));
                    }
                }
                else{
                    if(!(await provinsiRepository.add(new Provinsi{ID = new Guid(),provinsi = modProvinsi.provinsi.Trim()}))
                    )
                    {
                        ModelState.AddModelError(string.Empty, "Terjadi kesalahan, pastikan data telah terisi dengan benar!");
                    }
                    else
                    {
                        message = "Data Berhasil Disimpan";
                        // return RedirectToAction(nameof(index));
                    }
                }
            }
            else
            {
                if(!(await provinsiRepository.edit(modProvinsi)))
                {
                    ModelState.AddModelError("", "Terjadi kesalaham, pastikan data telah terisi dengan benar!");
                }
                else{
                    message = "Data berhasil disimpan";
                    // return RedirectToAction(nameof(index));
                }
            }
        } */
        
        public IActionResult tambah(){
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> tambah(Provinsi prov)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    if(prov.provinsi.Contains(';'))
                    {
                        string[] splitted = prov.provinsi.Split(';');
                        string added = "";
                        var state = false;
                        foreach (var str in splitted)
                        {
                            if(string.IsNullOrEmpty(str) || string.IsNullOrWhiteSpace(str))
                            {
                                state = true;
                                continue;
                            }

                            if(!(await provinsiRepository.add(new Provinsi{ID = new Guid(),provinsi = str.Trim()})))
                            {
                                if(!(string.IsNullOrEmpty(added)))
                                {
                                    added.Remove(added.Length - 1, 1);
                                }
                                state = false;
                                break;
                            }
                            else{
                                added += $" {str},";
                                state = true;
                                continue;
                            }
                        }
                        if(!state)
                        {
                            if(!(string.IsNullOrEmpty(added)))
                            {
                                ModelState.AddModelError(string.Empty, $"Terjadi kesalahan, pastikan data telah terisi dengan benar!, Provinsi{added} telah berhasil ditambahkan");
                            }else{
                                ModelState.AddModelError(string.Empty, $"Terjadi kesalahan, pastikan data telah terisi dengan benar!");
                            }
                        }else{
                            message = "Data Berhasil Disimpan";
                            return RedirectToAction(nameof(index));
                        }
                    }
                    else{
                        if(!(await provinsiRepository.add(new Provinsi{ID = new Guid(),provinsi = prov.provinsi.Trim()}))
                        )
                        {
                            ModelState.AddModelError(string.Empty, "Terjadi kesalahan, pastikan data telah terisi dengan benar!");
                        }
                        else
                        {
                            message = "Data Berhasil Disimpan";
                            return RedirectToAction(nameof(index));
                        }
                    }
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }
            return View(prov);
        }
        
        public async Task<IActionResult> edit(string ID)
        {

            var data = await provinsiRepository.readOneByID(ID);

            if(data == null)
            {
                message = "Terjadi kesalahan, provinsi tidak tersedia";
                return RedirectToAction(nameof(index));
            }
            return View(data);
        }
        
        [HttpPost]
        public async Task<IActionResult> edit(Provinsi prov)
        {
            if(ModelState.IsValid)
            {
                if(prov.provinsi.Contains(';'))
                {
                    ModelState.AddModelError("provinsi", "Penggunaan semicolon dilarang!");
                }
                else{
                    try
                    {
                        if(!(await provinsiRepository.edit(prov)))
                        {
                            ModelState.AddModelError("", "Terjadi kesalaham, pastikan data telah terisi dengan benar!");
                        }
                        else{
                            message = "Data berhasil disimpan";
                            return RedirectToAction(nameof(index));
                        }
                    }
                    catch (Exception e)
                    {
                        ModelState.AddModelError("", e.Message);
                        // return RedirectToAction("index", new{Area = "Administrator", message = });
                    }
                }
            }
            return View(prov);
        }

        
        public async Task<IActionResult> hapus(string ID)
        {
            try
            {
                if(!(await provinsiRepository.delete(_context.Provinsis.FirstOrDefault(p => p.ID.ToString() == ID)))
                )
                {
                    message = "Terjadi kesalahan, gagal menghapus!";
                    return RedirectToAction(nameof(index));
                }
                
                message = "Data berhasil dihapus";
                return RedirectToAction(nameof(index));

Areas/Administrator/Views/Provinsi/addOrEdit.cshtml
@{
    ViewData["Title"] = "Admin/Ubah Provinsi";
    Layout = null;
}
@model Provinsi

<form asp-action="edit" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="hidden" readonly asp-for="ID">
    <div class="form-group">
        <label class="form-label">Nama Provinsi</label>
        <input id="provinsi" type="text" class="form-control" asp-for="provinsi">
        <span asp-validation-for="provinsi" class="text-danger"></span>
    </div>
    <div class="form-group my-3">
        <div class="row">
            <div class="col-12">
                <button id="gotoPopup" style="width: 100%;" type="submit" class="btn btn-primary btn-block">Simpan</button>
            </div>
        </div>
        
    </div>
</form>


@section Scripts{
    <script>
        document.getElementById('provinsi').focus();

        if(!("@TempData["message"]" === ""))
        {
            alert("@TempData["message"]");
        }
    </script>
}

Areas/Administrator/Views/Provinsi/dihapus.cshtml
@{
    ViewData["Title"] = "Provinsi dibuang";
}
@model IEnumerable<ProvinsiDump>
<div class="text-center">
    <h1>Data Provinsi (Dibuang)</h1>
</div>
<hr>
<table class="table table-hover">
    <thead>
        <th class="text-center align-middle">Provinsi</th>
        <th class="text-center align-middle">Aksi</th>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="text-center align-middle">@item.provinsi</td>
                <td class="text-center align-middle">
                    <a style="color: black;" asp-action="pulihkan" asp-controller="Provinsi" asp-area="Administrator" asp-route-ID="@item.ID.ToString()" class="btn btn-outline-primary">Pulihkan</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <script>
        
        if(!("@TempData["message"]" === ""))
        {
            alert("@TempData["message"]")
        }
        
    </script>
}

Areas/Administrator/Views/Provinsi/edit.cshtml
@{
    ViewData["Title"] = "Admin/Ubah Provinsi";
}
@model Provinsi
<div class="text-center">
    <h4>Edit Data Provinsi</h4>
</div>

<form asp-action="edit" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="hidden" readonly asp-for="ID">
    <div class="form-group">
        <label class="form-label">Nama Provinsi</label>
        <input id="provinsi" type="text" class="form-control" asp-for="provinsi">
        <span asp-validation-for="provinsi" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Simpan</button>
        <a href='@Url.Action("index", "Provinsi", new{Area="Administrator"})' class="btn btn-outline-dark">Batal</a>
    </div>
</form>


@section Scripts{
    <script>
        document.getElementById('provinsi').focus();

        if(!("@TempData["message"]" === ""))
        {
            alert("@TempData["message"]");
        }
    </script>
}

Areas/Administrator/Views/Provinsi/index.cshtml
@{
    ViewData["Title"] = "Admin/Provinsi";
}
@model IEnumerable<Provinsi>
<div class="text-center">
    <h1>Data Provinsi</h1>
</div>
<hr>
@* <a style="margin-bottom: 10pt;" 
    onclick="gotoPopup('@Url.Action(action: "addOrEdit", controller: "Provinsi", new{Area = "Administrator"}, Context.Request.Scheme)','Tambah Provinsi')" 
    class="btn btn-outline-primary">
        <img width="20px" src="/svgs/regular/plus-square.svg" alt="Tambah">
        Tambah Provinsi
</a> *@

<button type="button" id="addEditModal" class="btn btn-outline-primary my-2" data-url='@Url.Action("addOrEdit", "Provinsi", new{Area = "Administrator"}, Context.Request.Scheme)' data-title="Tambah Provinsi" data-bs-toggle="modal" data-bs-target="#form-modal">Tambah Provinsi</button>

<a style="margin-bottom: 10pt; width: auto;" asp-action="dihapus" asp-controller="Provinsi" asp-area="Administrator" class="btn btn-outline-info">
        Daftar Provinsi yang dihapus
</a>
<table class="table table-hover">
    <thead>
        <th class="text-center align-middle">Provinsi</th>
        <th class="text-center align-middle">Aksi</th>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="text-center align-middle">@item.provinsi</td>
                <td class="text-center align-middle">
                    <a style="color: black;" href='@Url.Action("edit", "Provinsi", new{Area = "Administrator", ID = @item.ID.ToString()})' class="btn btn-outline-warning"><img style="border-right: 10px;" width="20px" src="/svgs/regular/edit.svg" alt="Edit">Edit</a>
                    <a style="color: black;" onclick="hapus('@item.ID.ToString()')" class="btn btn-outline-warning"><img style="border-right: 10px;" width="20px" src="/svgs/regular/trash-alt.svg" alt="Hapus">Hapus</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <script>
        
        if(!("@TempData["message"]" === ""))
        {
            alert("@TempData["message"]")
        }
        
        let hapus = function(param)
        {
            if(window.confirm("Yakin ingin memulihkan data ini?"))
            {
                window.location.href = "Provinsi/hapus/" + param;
            }
        }
    </script>
}

Areas/Administrator/Views/Provinsi/tambah.cshtml
@{
    ViewData["Title"] = "Admin/Tambah Provinsi";
}
@model Provinsi
<div class="text-center">
    <h4>Tambah Data Provinsi</h4>
</div>

<form asp-action="tambah" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label class="form-label">Nama Provinsi</label>
        <textarea id="provinsi" class="form-control" asp-for="provinsi"></textarea>
        <span style="display: block;">Untuk input lebih dari satu, pisahkan tiap-tiap <i>item</i> dengan <strong>semicolon (;)</strong></span>
        <span>Contoh: Provinsi A;Provinsi B;Provinsi C</span>
        <span style="display: block;" asp-validation-for="provinsi" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Simpan</button>
        <a href='@Url.Action("index", "Provinsi", new{Area="Administrator"})' class="btn btn-outline-dark">Batal</a>
    </div>
</form>

@section Scripts{
    <script>
        document.getElementById('provinsi').focus();
        if(!("@TempData["message"]" === ""))
        {
            alert("@TempData["message"]");
        }
    </script>
}