Areas/Administrator/Controllers/UsersController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OrigamiEdu.Models;
using System.Linq;

namespace OrigamiEdu.Areas.Administrator.Controllers
{
    // [Authorize(Roles = "Developer Master")]
    [Area("Administrator")]
    public class UsersController : Controller
    {
        private readonly UserManager<AppUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly Context context;

        public UsersController(UserManager<AppUser> userManager, RoleManager<IdentityRole> roleManager, Context context)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.context = context;
        }

        public async Task<IActionResult> index()
        {
            var _users = await userManager.Users.ToListAsync();
            return View(_users);
        }
    }
}

Controllers/AkunController.cs
using System;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OrigamiEdu.Helper;
using OrigamiEdu.Models;

namespace OrigamiEdu.Controllers
{
    public class AkunController : Controller
    {
        private readonly UserManager<AppUser> userManager;
        private readonly SignInManager<AppUser> signInManager;

        [TempData]
        public string message { get; set; }

        // private readonly UserManager<IdentityUser> _userManager;
        // private readonly SignInManager<IdentityUser> _signInManager;

        public AkunController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            // _userManager = userManager;
            // _signInManager = signInManager;
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Daftar()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Daftar([Bind("email", "username", "password", "confirmPass", "sex")] signUpModel model)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    // var customdate = getDateTime.getUTCTime(DateTime.Now);
                    var user = new AppUser{
                        UserName = model.username,
                        Email = model.email,
                        joinDate = DateTime.Now,
                        gender = model.sex == "Male" ? "M" : "F"
                    };
                    var result = await userManager.CreateAsync(user, model.password);
                    if(result.Succeeded)
                    {
                        /* ========== SETUP TYPE: ==========
                        [0] - completed
                        [1] - birthday - sekolah 
                        ==================================== */
                        // var roleResult = await userManager.AddToRoleAsync(user, "User");
                        // if(roleResult.Succeeded){
                            if(signInManager.IsSignedIn(User) && User.IsInRole("Developer Master"))
                            {
                                return RedirectToAction("index", "Users", new{Area = "Administrator"});
                            }
                            // await signInManager.SignInAsync(user, isPersistent:false);
                            TempData["message"] = "Akun telah berhasil didaftarkan";
                            return RedirectToAction("index", "home");
                        // }
                    }
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }
                catch (Exception e)
                {
                    message = e.Message;
                    return View(model);
                }
                
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Keluar()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("index", "home");
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Masuk(string returnUrl = null)
        {
            // var model = new UserInfo{ ReturnUrl = returnUrl};
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Masuk(signInModel modelUser, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if(ModelState.IsValid)
            {
                var result = await signInManager.PasswordSignInAsync(modelUser.username,modelUser.password,modelUser.rememberMe, false);

                if(result.Succeeded)
                {
                    if(!(string.IsNullOrEmpty(returnUrl)) && Url.IsLocalUrl(returnUrl))
                    {
                        return LocalRedirect(returnUrl);
                    }else{
                        return RedirectToAction("index", "home");
                    }
                }

                ModelState.AddModelError(string.Empty, "Nama Pengguna atau Kata Sandi salah!");
            }
            return View(modelUser);
        }

        public async Task<IActionResult> isEmailValid(string email)
        {
            string[] allowedDomain = new string[] {"gmail.com", "protonmail.com", "pm.me", "outlook.com", "hotmail.com"};

            if(string.IsNullOrWhiteSpace(email) || string.IsNullOrEmpty(email))
            {
                return Json("Mohon isi alamat surel Anda");
            }

            var dhawudad = "fardi@mail.com";


            string[] getDomain = email.Split('@');

            var domainValid = false;
            foreach (var item in allowedDomain)
            {
                if(getDomain[1].ToLower() == item.ToLower()){domainValid = true;break;}
            }
            if(!domainValid){
                return Json($"Saat ini domain alamat surel anda ({getDomain[1]}) belum didukung");
            }

            var user = await userManager.FindByEmailAsync(email);

            if(user == null && domainValid) return Json(true);
            
            return Json($"Alamat surel {email} telah dipakai");
        }

        public async Task<IActionResult> isUsernameValid(string username)
        {
            Regex regex = new Regex(@"(?!.*\.\.)(?!.*\.$)[^\W][\w.]{0,15}");
            Match match = regex.Match(username);

            if(match.Success)
            {
                var user = await userManager.FindByNameAsync(username);
                if(user == null)
                {
                    return Json(true);
                }
                return Json($"Nama pengguna '{username}' telah dipakai");
            }
            
            return Json($"Nama pengguna '{username}' tidak valid");

        }

        public IActionResult aksesDitolak()
        {
            return View();
        }
    }
}

Areas/Administrator/Views/Users/index.cshtml
@model IEnumerable<AppUser>

@{
    ViewData["Title"] = "Admin/Users";
}

<section class="text-center">
    <h1>Data Users</h1>
</section>

<section style="margin: 1rem 0;">
    <div class="float-right">
        <div class="form-inline">
            <div class="form group" style="width: auto;">
                <input type="text" id="searchQuery" name="query" class="form-control" placeholder="Cari User">
            </div>
        </div>
    </div>
    <a asp-action="Daftar" asp-area="" asp-controller="Akun" class="btn btn-outline-primary">
        <img width="20px" src="/svgs/regular/plus-square.svg" alt="Tambah">
        Tambah User Baru
    </a>    
</section>
<section>
        @if(Model.Any())
        {
            <table class="table table-hover" id="usersList">
                <thead>
                    <th class="text-center align-middle">Email</th>
                    <th class="text-center align-middle">Nama Pengguna</th>
                    <th class="text-center align-middle">Nama</th>
                    <th class="text-center align-middle">Joined</th>
                    <th class="text-center align-middle">Aksi</th>
                </thead>
                <tbody>
                    @foreach(var _user in Model)
                    {
                        <tr class="text-center align-middle">
                            <td>
                                @_user.Email
                            </td>
                            <td>@_user.UserName</td>
                            <td>@_user.UserName</td>
                            <td>@_user.joinDate.ToString("dd/MM/yyyy - HH:mm:ss 'GMT'z")</td>
                            <td>
                                <buttton class="btn btn-outline-danger" style="width: auto;">Ban (cabut akses)</buttton>
                                <buttton class="btn btn-outline-info" style="width: auto;">Atur Ulang Info</buttton>
                                <buttton class="btn btn-outline-info" style="width: auto;">Kirim Email</buttton>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
</section>

@section Scripts
{
    <script>
        if(!("@TempData["message"]" === ""))
        {
            alert("@TempData["message"]");
        }

        $(document).ready(function(){
            var usersList = $("#usersList").DataTable({
                @* "pagingType" : "full_numbers", *@
                "dom":' ltp'
            });
            $('#searchQuery').keyup(function(){
                usersList.search($(this).val()).draw() ;
            });
        })
    </script>
}